package com.bb.emaildemo.model;

import java.util.Date;

public class Email {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column email.e_id
     *
     * @mbggenerated
     */
    private Integer eId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column email.e_theme
     *
     * @mbggenerated
     */
    private String eTheme;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column email.e_sendpeople
     *
     * @mbggenerated
     */
    private Integer eSendpeople;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column email.e_receive
     *
     * @mbggenerated
     */
    private Integer eReceive;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column email.e_orread
     *
     * @mbggenerated
     */
    private String eOrread;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column email.e_orsend
     *
     * @mbggenerated
     */
    private String eOrsend;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column email.e_ordelete
     *
     * @mbggenerated
     */
    private String eOrdelete;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column email.e_orcollection
     *
     * @mbggenerated
     */
    private String eOrcollection;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column email.e_sendtime
     *
     * @mbggenerated
     */
    private Date eSendtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column email.e_fileurl
     *
     * @mbggenerated
     */
    private String eFileurl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column email.e__content
     *
     * @mbggenerated
     */
    private String eContent;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column email.e_id
     *
     * @return the value of email.e_id
     *
     * @mbggenerated
     */
    public Integer geteId() {
        return eId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column email.e_id
     *
     * @param eId the value for email.e_id
     *
     * @mbggenerated
     */
    public void seteId(Integer eId) {
        this.eId = eId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column email.e_theme
     *
     * @return the value of email.e_theme
     *
     * @mbggenerated
     */
    public String geteTheme() {
        return eTheme;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column email.e_theme
     *
     * @param eTheme the value for email.e_theme
     *
     * @mbggenerated
     */
    public void seteTheme(String eTheme) {
        this.eTheme = eTheme == null ? null : eTheme.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column email.e_sendpeople
     *
     * @return the value of email.e_sendpeople
     *
     * @mbggenerated
     */
    public Integer geteSendpeople() {
        return eSendpeople;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column email.e_sendpeople
     *
     * @param eSendpeople the value for email.e_sendpeople
     *
     * @mbggenerated
     */
    public void seteSendpeople(Integer eSendpeople) {
        this.eSendpeople = eSendpeople;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column email.e_receive
     *
     * @return the value of email.e_receive
     *
     * @mbggenerated
     */
    public Integer geteReceive() {
        return eReceive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column email.e_receive
     *
     * @param eReceive the value for email.e_receive
     *
     * @mbggenerated
     */
    public void seteReceive(Integer eReceive) {
        this.eReceive = eReceive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column email.e_orread
     *
     * @return the value of email.e_orread
     *
     * @mbggenerated
     */
    public String geteOrread() {
        return eOrread;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column email.e_orread
     *
     * @param eOrread the value for email.e_orread
     *
     * @mbggenerated
     */
    public void seteOrread(String eOrread) {
        this.eOrread = eOrread == null ? null : eOrread.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column email.e_orsend
     *
     * @return the value of email.e_orsend
     *
     * @mbggenerated
     */
    public String geteOrsend() {
        return eOrsend;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column email.e_orsend
     *
     * @param eOrsend the value for email.e_orsend
     *
     * @mbggenerated
     */
    public void seteOrsend(String eOrsend) {
        this.eOrsend = eOrsend == null ? null : eOrsend.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column email.e_ordelete
     *
     * @return the value of email.e_ordelete
     *
     * @mbggenerated
     */
    public String geteOrdelete() {
        return eOrdelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column email.e_ordelete
     *
     * @param eOrdelete the value for email.e_ordelete
     *
     * @mbggenerated
     */
    public void seteOrdelete(String eOrdelete) {
        this.eOrdelete = eOrdelete == null ? null : eOrdelete.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column email.e_orcollection
     *
     * @return the value of email.e_orcollection
     *
     * @mbggenerated
     */
    public String geteOrcollection() {
        return eOrcollection;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column email.e_orcollection
     *
     * @param eOrcollection the value for email.e_orcollection
     *
     * @mbggenerated
     */
    public void seteOrcollection(String eOrcollection) {
        this.eOrcollection = eOrcollection == null ? null : eOrcollection.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column email.e_sendtime
     *
     * @return the value of email.e_sendtime
     *
     * @mbggenerated
     */
    public Date geteSendtime() {
        return eSendtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column email.e_sendtime
     *
     * @param eSendtime the value for email.e_sendtime
     *
     * @mbggenerated
     */
    public void seteSendtime(Date eSendtime) {
        this.eSendtime = eSendtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column email.e_fileurl
     *
     * @return the value of email.e_fileurl
     *
     * @mbggenerated
     */
    public String geteFileurl() {
        return eFileurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column email.e_fileurl
     *
     * @param eFileurl the value for email.e_fileurl
     *
     * @mbggenerated
     */
    public void seteFileurl(String eFileurl) {
        this.eFileurl = eFileurl == null ? null : eFileurl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column email.e__content
     *
     * @return the value of email.e__content
     *
     * @mbggenerated
     */
    public String geteContent() {
        return eContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column email.e__content
     *
     * @param eContent the value for email.e__content
     *
     * @mbggenerated
     */
    public void seteContent(String eContent) {
        this.eContent = eContent == null ? null : eContent.trim();
    }
}