package com.bb.emaildemo.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class FriendsExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table friends
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table friends
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table friends
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table friends
     *
     * @mbggenerated
     */
    public FriendsExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table friends
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table friends
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table friends
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table friends
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table friends
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table friends
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table friends
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table friends
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table friends
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table friends
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table friends
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andFIdIsNull() {
            addCriterion("f_id is null");
            return (Criteria) this;
        }

        public Criteria andFIdIsNotNull() {
            addCriterion("f_id is not null");
            return (Criteria) this;
        }

        public Criteria andFIdEqualTo(Integer value) {
            addCriterion("f_id =", value, "fId");
            return (Criteria) this;
        }

        public Criteria andFIdNotEqualTo(Integer value) {
            addCriterion("f_id <>", value, "fId");
            return (Criteria) this;
        }

        public Criteria andFIdGreaterThan(Integer value) {
            addCriterion("f_id >", value, "fId");
            return (Criteria) this;
        }

        public Criteria andFIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("f_id >=", value, "fId");
            return (Criteria) this;
        }

        public Criteria andFIdLessThan(Integer value) {
            addCriterion("f_id <", value, "fId");
            return (Criteria) this;
        }

        public Criteria andFIdLessThanOrEqualTo(Integer value) {
            addCriterion("f_id <=", value, "fId");
            return (Criteria) this;
        }

        public Criteria andFIdIn(List<Integer> values) {
            addCriterion("f_id in", values, "fId");
            return (Criteria) this;
        }

        public Criteria andFIdNotIn(List<Integer> values) {
            addCriterion("f_id not in", values, "fId");
            return (Criteria) this;
        }

        public Criteria andFIdBetween(Integer value1, Integer value2) {
            addCriterion("f_id between", value1, value2, "fId");
            return (Criteria) this;
        }

        public Criteria andFIdNotBetween(Integer value1, Integer value2) {
            addCriterion("f_id not between", value1, value2, "fId");
            return (Criteria) this;
        }

        public Criteria andFUserIsNull() {
            addCriterion("f_user is null");
            return (Criteria) this;
        }

        public Criteria andFUserIsNotNull() {
            addCriterion("f_user is not null");
            return (Criteria) this;
        }

        public Criteria andFUserEqualTo(Integer value) {
            addCriterion("f_user =", value, "fUser");
            return (Criteria) this;
        }

        public Criteria andFUserNotEqualTo(Integer value) {
            addCriterion("f_user <>", value, "fUser");
            return (Criteria) this;
        }

        public Criteria andFUserGreaterThan(Integer value) {
            addCriterion("f_user >", value, "fUser");
            return (Criteria) this;
        }

        public Criteria andFUserGreaterThanOrEqualTo(Integer value) {
            addCriterion("f_user >=", value, "fUser");
            return (Criteria) this;
        }

        public Criteria andFUserLessThan(Integer value) {
            addCriterion("f_user <", value, "fUser");
            return (Criteria) this;
        }

        public Criteria andFUserLessThanOrEqualTo(Integer value) {
            addCriterion("f_user <=", value, "fUser");
            return (Criteria) this;
        }

        public Criteria andFUserIn(List<Integer> values) {
            addCriterion("f_user in", values, "fUser");
            return (Criteria) this;
        }

        public Criteria andFUserNotIn(List<Integer> values) {
            addCriterion("f_user not in", values, "fUser");
            return (Criteria) this;
        }

        public Criteria andFUserBetween(Integer value1, Integer value2) {
            addCriterion("f_user between", value1, value2, "fUser");
            return (Criteria) this;
        }

        public Criteria andFUserNotBetween(Integer value1, Integer value2) {
            addCriterion("f_user not between", value1, value2, "fUser");
            return (Criteria) this;
        }

        public Criteria andFFriendIsNull() {
            addCriterion("f_friend is null");
            return (Criteria) this;
        }

        public Criteria andFFriendIsNotNull() {
            addCriterion("f_friend is not null");
            return (Criteria) this;
        }

        public Criteria andFFriendEqualTo(Integer value) {
            addCriterion("f_friend =", value, "fFriend");
            return (Criteria) this;
        }

        public Criteria andFFriendNotEqualTo(Integer value) {
            addCriterion("f_friend <>", value, "fFriend");
            return (Criteria) this;
        }

        public Criteria andFFriendGreaterThan(Integer value) {
            addCriterion("f_friend >", value, "fFriend");
            return (Criteria) this;
        }

        public Criteria andFFriendGreaterThanOrEqualTo(Integer value) {
            addCriterion("f_friend >=", value, "fFriend");
            return (Criteria) this;
        }

        public Criteria andFFriendLessThan(Integer value) {
            addCriterion("f_friend <", value, "fFriend");
            return (Criteria) this;
        }

        public Criteria andFFriendLessThanOrEqualTo(Integer value) {
            addCriterion("f_friend <=", value, "fFriend");
            return (Criteria) this;
        }

        public Criteria andFFriendIn(List<Integer> values) {
            addCriterion("f_friend in", values, "fFriend");
            return (Criteria) this;
        }

        public Criteria andFFriendNotIn(List<Integer> values) {
            addCriterion("f_friend not in", values, "fFriend");
            return (Criteria) this;
        }

        public Criteria andFFriendBetween(Integer value1, Integer value2) {
            addCriterion("f_friend between", value1, value2, "fFriend");
            return (Criteria) this;
        }

        public Criteria andFFriendNotBetween(Integer value1, Integer value2) {
            addCriterion("f_friend not between", value1, value2, "fFriend");
            return (Criteria) this;
        }

        public Criteria andFCreatetimeIsNull() {
            addCriterion("f_createtime is null");
            return (Criteria) this;
        }

        public Criteria andFCreatetimeIsNotNull() {
            addCriterion("f_createtime is not null");
            return (Criteria) this;
        }

        public Criteria andFCreatetimeEqualTo(Date value) {
            addCriterion("f_createtime =", value, "fCreatetime");
            return (Criteria) this;
        }

        public Criteria andFCreatetimeNotEqualTo(Date value) {
            addCriterion("f_createtime <>", value, "fCreatetime");
            return (Criteria) this;
        }

        public Criteria andFCreatetimeGreaterThan(Date value) {
            addCriterion("f_createtime >", value, "fCreatetime");
            return (Criteria) this;
        }

        public Criteria andFCreatetimeGreaterThanOrEqualTo(Date value) {
            addCriterion("f_createtime >=", value, "fCreatetime");
            return (Criteria) this;
        }

        public Criteria andFCreatetimeLessThan(Date value) {
            addCriterion("f_createtime <", value, "fCreatetime");
            return (Criteria) this;
        }

        public Criteria andFCreatetimeLessThanOrEqualTo(Date value) {
            addCriterion("f_createtime <=", value, "fCreatetime");
            return (Criteria) this;
        }

        public Criteria andFCreatetimeIn(List<Date> values) {
            addCriterion("f_createtime in", values, "fCreatetime");
            return (Criteria) this;
        }

        public Criteria andFCreatetimeNotIn(List<Date> values) {
            addCriterion("f_createtime not in", values, "fCreatetime");
            return (Criteria) this;
        }

        public Criteria andFCreatetimeBetween(Date value1, Date value2) {
            addCriterion("f_createtime between", value1, value2, "fCreatetime");
            return (Criteria) this;
        }

        public Criteria andFCreatetimeNotBetween(Date value1, Date value2) {
            addCriterion("f_createtime not between", value1, value2, "fCreatetime");
            return (Criteria) this;
        }

        public Criteria andFRemarkIsNull() {
            addCriterion("f_remark is null");
            return (Criteria) this;
        }

        public Criteria andFRemarkIsNotNull() {
            addCriterion("f_remark is not null");
            return (Criteria) this;
        }

        public Criteria andFRemarkEqualTo(String value) {
            addCriterion("f_remark =", value, "fRemark");
            return (Criteria) this;
        }

        public Criteria andFRemarkNotEqualTo(String value) {
            addCriterion("f_remark <>", value, "fRemark");
            return (Criteria) this;
        }

        public Criteria andFRemarkGreaterThan(String value) {
            addCriterion("f_remark >", value, "fRemark");
            return (Criteria) this;
        }

        public Criteria andFRemarkGreaterThanOrEqualTo(String value) {
            addCriterion("f_remark >=", value, "fRemark");
            return (Criteria) this;
        }

        public Criteria andFRemarkLessThan(String value) {
            addCriterion("f_remark <", value, "fRemark");
            return (Criteria) this;
        }

        public Criteria andFRemarkLessThanOrEqualTo(String value) {
            addCriterion("f_remark <=", value, "fRemark");
            return (Criteria) this;
        }

        public Criteria andFRemarkLike(String value) {
            addCriterion("f_remark like", value, "fRemark");
            return (Criteria) this;
        }

        public Criteria andFRemarkNotLike(String value) {
            addCriterion("f_remark not like", value, "fRemark");
            return (Criteria) this;
        }

        public Criteria andFRemarkIn(List<String> values) {
            addCriterion("f_remark in", values, "fRemark");
            return (Criteria) this;
        }

        public Criteria andFRemarkNotIn(List<String> values) {
            addCriterion("f_remark not in", values, "fRemark");
            return (Criteria) this;
        }

        public Criteria andFRemarkBetween(String value1, String value2) {
            addCriterion("f_remark between", value1, value2, "fRemark");
            return (Criteria) this;
        }

        public Criteria andFRemarkNotBetween(String value1, String value2) {
            addCriterion("f_remark not between", value1, value2, "fRemark");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table friends
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table friends
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}