package com.bb.emaildemo.model;

import java.util.Date;

public class Friends {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column friends.f_id
     *
     * @mbggenerated
     */
    private Integer fId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column friends.f_user
     *
     * @mbggenerated
     */
    private Integer fUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column friends.f_friend
     *
     * @mbggenerated
     */
    private Integer fFriend;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column friends.f_createtime
     *
     * @mbggenerated
     */
    private Date fCreatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column friends.f_remark
     *
     * @mbggenerated
     */
    private String fRemark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column friends.f_id
     *
     * @return the value of friends.f_id
     *
     * @mbggenerated
     */
    public Integer getfId() {
        return fId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column friends.f_id
     *
     * @param fId the value for friends.f_id
     *
     * @mbggenerated
     */
    public void setfId(Integer fId) {
        this.fId = fId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column friends.f_user
     *
     * @return the value of friends.f_user
     *
     * @mbggenerated
     */
    public Integer getfUser() {
        return fUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column friends.f_user
     *
     * @param fUser the value for friends.f_user
     *
     * @mbggenerated
     */
    public void setfUser(Integer fUser) {
        this.fUser = fUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column friends.f_friend
     *
     * @return the value of friends.f_friend
     *
     * @mbggenerated
     */
    public Integer getfFriend() {
        return fFriend;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column friends.f_friend
     *
     * @param fFriend the value for friends.f_friend
     *
     * @mbggenerated
     */
    public void setfFriend(Integer fFriend) {
        this.fFriend = fFriend;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column friends.f_createtime
     *
     * @return the value of friends.f_createtime
     *
     * @mbggenerated
     */
    public Date getfCreatetime() {
        return fCreatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column friends.f_createtime
     *
     * @param fCreatetime the value for friends.f_createtime
     *
     * @mbggenerated
     */
    public void setfCreatetime(Date fCreatetime) {
        this.fCreatetime = fCreatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column friends.f_remark
     *
     * @return the value of friends.f_remark
     *
     * @mbggenerated
     */
    public String getfRemark() {
        return fRemark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column friends.f_remark
     *
     * @param fRemark the value for friends.f_remark
     *
     * @mbggenerated
     */
    public void setfRemark(String fRemark) {
        this.fRemark = fRemark == null ? null : fRemark.trim();
    }
}