package com.bb.emaildemo.model;

import java.util.ArrayList;
import java.util.List;

public class UserinfoExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table userinfo
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table userinfo
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table userinfo
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userinfo
     *
     * @mbggenerated
     */
    public UserinfoExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userinfo
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userinfo
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userinfo
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userinfo
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userinfo
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userinfo
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userinfo
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userinfo
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userinfo
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userinfo
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table userinfo
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andInfoIdIsNull() {
            addCriterion("info_id is null");
            return (Criteria) this;
        }

        public Criteria andInfoIdIsNotNull() {
            addCriterion("info_id is not null");
            return (Criteria) this;
        }

        public Criteria andInfoIdEqualTo(Integer value) {
            addCriterion("info_id =", value, "infoId");
            return (Criteria) this;
        }

        public Criteria andInfoIdNotEqualTo(Integer value) {
            addCriterion("info_id <>", value, "infoId");
            return (Criteria) this;
        }

        public Criteria andInfoIdGreaterThan(Integer value) {
            addCriterion("info_id >", value, "infoId");
            return (Criteria) this;
        }

        public Criteria andInfoIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("info_id >=", value, "infoId");
            return (Criteria) this;
        }

        public Criteria andInfoIdLessThan(Integer value) {
            addCriterion("info_id <", value, "infoId");
            return (Criteria) this;
        }

        public Criteria andInfoIdLessThanOrEqualTo(Integer value) {
            addCriterion("info_id <=", value, "infoId");
            return (Criteria) this;
        }

        public Criteria andInfoIdIn(List<Integer> values) {
            addCriterion("info_id in", values, "infoId");
            return (Criteria) this;
        }

        public Criteria andInfoIdNotIn(List<Integer> values) {
            addCriterion("info_id not in", values, "infoId");
            return (Criteria) this;
        }

        public Criteria andInfoIdBetween(Integer value1, Integer value2) {
            addCriterion("info_id between", value1, value2, "infoId");
            return (Criteria) this;
        }

        public Criteria andInfoIdNotBetween(Integer value1, Integer value2) {
            addCriterion("info_id not between", value1, value2, "infoId");
            return (Criteria) this;
        }

        public Criteria andInfoRemarkIsNull() {
            addCriterion("info_remark is null");
            return (Criteria) this;
        }

        public Criteria andInfoRemarkIsNotNull() {
            addCriterion("info_remark is not null");
            return (Criteria) this;
        }

        public Criteria andInfoRemarkEqualTo(String value) {
            addCriterion("info_remark =", value, "infoRemark");
            return (Criteria) this;
        }

        public Criteria andInfoRemarkNotEqualTo(String value) {
            addCriterion("info_remark <>", value, "infoRemark");
            return (Criteria) this;
        }

        public Criteria andInfoRemarkGreaterThan(String value) {
            addCriterion("info_remark >", value, "infoRemark");
            return (Criteria) this;
        }

        public Criteria andInfoRemarkGreaterThanOrEqualTo(String value) {
            addCriterion("info_remark >=", value, "infoRemark");
            return (Criteria) this;
        }

        public Criteria andInfoRemarkLessThan(String value) {
            addCriterion("info_remark <", value, "infoRemark");
            return (Criteria) this;
        }

        public Criteria andInfoRemarkLessThanOrEqualTo(String value) {
            addCriterion("info_remark <=", value, "infoRemark");
            return (Criteria) this;
        }

        public Criteria andInfoRemarkLike(String value) {
            addCriterion("info_remark like", value, "infoRemark");
            return (Criteria) this;
        }

        public Criteria andInfoRemarkNotLike(String value) {
            addCriterion("info_remark not like", value, "infoRemark");
            return (Criteria) this;
        }

        public Criteria andInfoRemarkIn(List<String> values) {
            addCriterion("info_remark in", values, "infoRemark");
            return (Criteria) this;
        }

        public Criteria andInfoRemarkNotIn(List<String> values) {
            addCriterion("info_remark not in", values, "infoRemark");
            return (Criteria) this;
        }

        public Criteria andInfoRemarkBetween(String value1, String value2) {
            addCriterion("info_remark between", value1, value2, "infoRemark");
            return (Criteria) this;
        }

        public Criteria andInfoRemarkNotBetween(String value1, String value2) {
            addCriterion("info_remark not between", value1, value2, "infoRemark");
            return (Criteria) this;
        }

        public Criteria andInfoHeadimgIsNull() {
            addCriterion("info_headimg is null");
            return (Criteria) this;
        }

        public Criteria andInfoHeadimgIsNotNull() {
            addCriterion("info_headimg is not null");
            return (Criteria) this;
        }

        public Criteria andInfoHeadimgEqualTo(String value) {
            addCriterion("info_headimg =", value, "infoHeadimg");
            return (Criteria) this;
        }

        public Criteria andInfoHeadimgNotEqualTo(String value) {
            addCriterion("info_headimg <>", value, "infoHeadimg");
            return (Criteria) this;
        }

        public Criteria andInfoHeadimgGreaterThan(String value) {
            addCriterion("info_headimg >", value, "infoHeadimg");
            return (Criteria) this;
        }

        public Criteria andInfoHeadimgGreaterThanOrEqualTo(String value) {
            addCriterion("info_headimg >=", value, "infoHeadimg");
            return (Criteria) this;
        }

        public Criteria andInfoHeadimgLessThan(String value) {
            addCriterion("info_headimg <", value, "infoHeadimg");
            return (Criteria) this;
        }

        public Criteria andInfoHeadimgLessThanOrEqualTo(String value) {
            addCriterion("info_headimg <=", value, "infoHeadimg");
            return (Criteria) this;
        }

        public Criteria andInfoHeadimgLike(String value) {
            addCriterion("info_headimg like", value, "infoHeadimg");
            return (Criteria) this;
        }

        public Criteria andInfoHeadimgNotLike(String value) {
            addCriterion("info_headimg not like", value, "infoHeadimg");
            return (Criteria) this;
        }

        public Criteria andInfoHeadimgIn(List<String> values) {
            addCriterion("info_headimg in", values, "infoHeadimg");
            return (Criteria) this;
        }

        public Criteria andInfoHeadimgNotIn(List<String> values) {
            addCriterion("info_headimg not in", values, "infoHeadimg");
            return (Criteria) this;
        }

        public Criteria andInfoHeadimgBetween(String value1, String value2) {
            addCriterion("info_headimg between", value1, value2, "infoHeadimg");
            return (Criteria) this;
        }

        public Criteria andInfoHeadimgNotBetween(String value1, String value2) {
            addCriterion("info_headimg not between", value1, value2, "infoHeadimg");
            return (Criteria) this;
        }

        public Criteria andInfoSignIsNull() {
            addCriterion("info_sign is null");
            return (Criteria) this;
        }

        public Criteria andInfoSignIsNotNull() {
            addCriterion("info_sign is not null");
            return (Criteria) this;
        }

        public Criteria andInfoSignEqualTo(String value) {
            addCriterion("info_sign =", value, "infoSign");
            return (Criteria) this;
        }

        public Criteria andInfoSignNotEqualTo(String value) {
            addCriterion("info_sign <>", value, "infoSign");
            return (Criteria) this;
        }

        public Criteria andInfoSignGreaterThan(String value) {
            addCriterion("info_sign >", value, "infoSign");
            return (Criteria) this;
        }

        public Criteria andInfoSignGreaterThanOrEqualTo(String value) {
            addCriterion("info_sign >=", value, "infoSign");
            return (Criteria) this;
        }

        public Criteria andInfoSignLessThan(String value) {
            addCriterion("info_sign <", value, "infoSign");
            return (Criteria) this;
        }

        public Criteria andInfoSignLessThanOrEqualTo(String value) {
            addCriterion("info_sign <=", value, "infoSign");
            return (Criteria) this;
        }

        public Criteria andInfoSignLike(String value) {
            addCriterion("info_sign like", value, "infoSign");
            return (Criteria) this;
        }

        public Criteria andInfoSignNotLike(String value) {
            addCriterion("info_sign not like", value, "infoSign");
            return (Criteria) this;
        }

        public Criteria andInfoSignIn(List<String> values) {
            addCriterion("info_sign in", values, "infoSign");
            return (Criteria) this;
        }

        public Criteria andInfoSignNotIn(List<String> values) {
            addCriterion("info_sign not in", values, "infoSign");
            return (Criteria) this;
        }

        public Criteria andInfoSignBetween(String value1, String value2) {
            addCriterion("info_sign between", value1, value2, "infoSign");
            return (Criteria) this;
        }

        public Criteria andInfoSignNotBetween(String value1, String value2) {
            addCriterion("info_sign not between", value1, value2, "infoSign");
            return (Criteria) this;
        }

        public Criteria andInfoSexIsNull() {
            addCriterion("info_sex is null");
            return (Criteria) this;
        }

        public Criteria andInfoSexIsNotNull() {
            addCriterion("info_sex is not null");
            return (Criteria) this;
        }

        public Criteria andInfoSexEqualTo(String value) {
            addCriterion("info_sex =", value, "infoSex");
            return (Criteria) this;
        }

        public Criteria andInfoSexNotEqualTo(String value) {
            addCriterion("info_sex <>", value, "infoSex");
            return (Criteria) this;
        }

        public Criteria andInfoSexGreaterThan(String value) {
            addCriterion("info_sex >", value, "infoSex");
            return (Criteria) this;
        }

        public Criteria andInfoSexGreaterThanOrEqualTo(String value) {
            addCriterion("info_sex >=", value, "infoSex");
            return (Criteria) this;
        }

        public Criteria andInfoSexLessThan(String value) {
            addCriterion("info_sex <", value, "infoSex");
            return (Criteria) this;
        }

        public Criteria andInfoSexLessThanOrEqualTo(String value) {
            addCriterion("info_sex <=", value, "infoSex");
            return (Criteria) this;
        }

        public Criteria andInfoSexLike(String value) {
            addCriterion("info_sex like", value, "infoSex");
            return (Criteria) this;
        }

        public Criteria andInfoSexNotLike(String value) {
            addCriterion("info_sex not like", value, "infoSex");
            return (Criteria) this;
        }

        public Criteria andInfoSexIn(List<String> values) {
            addCriterion("info_sex in", values, "infoSex");
            return (Criteria) this;
        }

        public Criteria andInfoSexNotIn(List<String> values) {
            addCriterion("info_sex not in", values, "infoSex");
            return (Criteria) this;
        }

        public Criteria andInfoSexBetween(String value1, String value2) {
            addCriterion("info_sex between", value1, value2, "infoSex");
            return (Criteria) this;
        }

        public Criteria andInfoSexNotBetween(String value1, String value2) {
            addCriterion("info_sex not between", value1, value2, "infoSex");
            return (Criteria) this;
        }

        public Criteria andInfoUserIsNull() {
            addCriterion("info_user is null");
            return (Criteria) this;
        }

        public Criteria andInfoUserIsNotNull() {
            addCriterion("info_user is not null");
            return (Criteria) this;
        }

        public Criteria andInfoUserEqualTo(Integer value) {
            addCriterion("info_user =", value, "infoUser");
            return (Criteria) this;
        }

        public Criteria andInfoUserNotEqualTo(Integer value) {
            addCriterion("info_user <>", value, "infoUser");
            return (Criteria) this;
        }

        public Criteria andInfoUserGreaterThan(Integer value) {
            addCriterion("info_user >", value, "infoUser");
            return (Criteria) this;
        }

        public Criteria andInfoUserGreaterThanOrEqualTo(Integer value) {
            addCriterion("info_user >=", value, "infoUser");
            return (Criteria) this;
        }

        public Criteria andInfoUserLessThan(Integer value) {
            addCriterion("info_user <", value, "infoUser");
            return (Criteria) this;
        }

        public Criteria andInfoUserLessThanOrEqualTo(Integer value) {
            addCriterion("info_user <=", value, "infoUser");
            return (Criteria) this;
        }

        public Criteria andInfoUserIn(List<Integer> values) {
            addCriterion("info_user in", values, "infoUser");
            return (Criteria) this;
        }

        public Criteria andInfoUserNotIn(List<Integer> values) {
            addCriterion("info_user not in", values, "infoUser");
            return (Criteria) this;
        }

        public Criteria andInfoUserBetween(Integer value1, Integer value2) {
            addCriterion("info_user between", value1, value2, "infoUser");
            return (Criteria) this;
        }

        public Criteria andInfoUserNotBetween(Integer value1, Integer value2) {
            addCriterion("info_user not between", value1, value2, "infoUser");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table userinfo
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table userinfo
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}