package com.bb.emaildemo.model;

import java.util.Date;

public class User {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.u_flogid
     *
     * @mbggenerated
     */
    private Integer uFlogid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.u_id
     *
     * @mbggenerated
     */
    private Integer uId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.u_password
     *
     * @mbggenerated
     */
    private String uPassword;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.u_createtime
     *
     * @mbggenerated
     */
    private Date uCreatetime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.u_flogid
     *
     * @return the value of user.u_flogid
     *
     * @mbggenerated
     */
    public Integer getuFlogid() {
        return uFlogid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.u_flogid
     *
     * @param uFlogid the value for user.u_flogid
     *
     * @mbggenerated
     */
    public void setuFlogid(Integer uFlogid) {
        this.uFlogid = uFlogid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.u_id
     *
     * @return the value of user.u_id
     *
     * @mbggenerated
     */
    public Integer getuId() {
        return uId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.u_id
     *
     * @param uId the value for user.u_id
     *
     * @mbggenerated
     */
    public void setuId(Integer uId) {
        this.uId = uId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.u_password
     *
     * @return the value of user.u_password
     *
     * @mbggenerated
     */
    public String getuPassword() {
        return uPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.u_password
     *
     * @param uPassword the value for user.u_password
     *
     * @mbggenerated
     */
    public void setuPassword(String uPassword) {
        this.uPassword = uPassword == null ? null : uPassword.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.u_createtime
     *
     * @return the value of user.u_createtime
     *
     * @mbggenerated
     */
    public Date getuCreatetime() {
        return uCreatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.u_createtime
     *
     * @param uCreatetime the value for user.u_createtime
     *
     * @mbggenerated
     */
    public void setuCreatetime(Date uCreatetime) {
        this.uCreatetime = uCreatetime;
    }
}