package com.bb.emaildemo.model;

public class Userinfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfo.info_id
     *
     * @mbggenerated
     */
    private Integer infoId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfo.info_remark
     *
     * @mbggenerated
     */
    private String infoRemark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfo.info_headimg
     *
     * @mbggenerated
     */
    private String infoHeadimg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfo.info_sign
     *
     * @mbggenerated
     */
    private String infoSign;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfo.info_sex
     *
     * @mbggenerated
     */
    private String infoSex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfo.info_user
     *
     * @mbggenerated
     */
    private Integer infoUser;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userinfo.info_id
     *
     * @return the value of userinfo.info_id
     *
     * @mbggenerated
     */
    public Integer getInfoId() {
        return infoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userinfo.info_id
     *
     * @param infoId the value for userinfo.info_id
     *
     * @mbggenerated
     */
    public void setInfoId(Integer infoId) {
        this.infoId = infoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userinfo.info_remark
     *
     * @return the value of userinfo.info_remark
     *
     * @mbggenerated
     */
    public String getInfoRemark() {
        return infoRemark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userinfo.info_remark
     *
     * @param infoRemark the value for userinfo.info_remark
     *
     * @mbggenerated
     */
    public void setInfoRemark(String infoRemark) {
        this.infoRemark = infoRemark == null ? null : infoRemark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userinfo.info_headimg
     *
     * @return the value of userinfo.info_headimg
     *
     * @mbggenerated
     */
    public String getInfoHeadimg() {
        return infoHeadimg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userinfo.info_headimg
     *
     * @param infoHeadimg the value for userinfo.info_headimg
     *
     * @mbggenerated
     */
    public void setInfoHeadimg(String infoHeadimg) {
        this.infoHeadimg = infoHeadimg == null ? null : infoHeadimg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userinfo.info_sign
     *
     * @return the value of userinfo.info_sign
     *
     * @mbggenerated
     */
    public String getInfoSign() {
        return infoSign;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userinfo.info_sign
     *
     * @param infoSign the value for userinfo.info_sign
     *
     * @mbggenerated
     */
    public void setInfoSign(String infoSign) {
        this.infoSign = infoSign == null ? null : infoSign.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userinfo.info_sex
     *
     * @return the value of userinfo.info_sex
     *
     * @mbggenerated
     */
    public String getInfoSex() {
        return infoSex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userinfo.info_sex
     *
     * @param infoSex the value for userinfo.info_sex
     *
     * @mbggenerated
     */
    public void setInfoSex(String infoSex) {
        this.infoSex = infoSex == null ? null : infoSex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userinfo.info_user
     *
     * @return the value of userinfo.info_user
     *
     * @mbggenerated
     */
    public Integer getInfoUser() {
        return infoUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userinfo.info_user
     *
     * @param infoUser the value for userinfo.info_user
     *
     * @mbggenerated
     */
    public void setInfoUser(Integer infoUser) {
        this.infoUser = infoUser;
    }
}